### ISSUE TITLE
Allow configurable GeoIP database path

### ISSUE THREAD

**Issue by hjelmevold** [enonic/lib-geoip#33]
lib-geoip is currently hardcoded to look for `${xp.home}/config/GeoLite2-City.mmdb`, but many environments restrict write access to XP_HOME/config for security reasons, which makes it difficult to keep this database up to date by uploading new versions of that file to the server (e.g. using app-gitpull)

I imagine making the path configurable can be done similar to [how app-google-analytics has a configurable path to its p12 file](https://github.com/enonic/app-google-analytics/blob/master/src/main/java/com/enonic/app/ga/rest/auth/GoogleAnalyticsAuthenticationService.java#L41)

**Comment by alansemenov** [comment]
@hjelmevold where is this database coming from? is it out in the open? can it be downloaded via simple request (without complex authentication)? if yes, then maybe a better approach would be to download it and cache until it changes? then we make sure it's always up-do-date.

**Comment by hjelmevold** [comment]
It's no longer as easy as it was when the documentation for lib-geoip was written (the link in the current doc gives 404)

> You will need a free GeoLite2 account to download the GeoLite2 databases or to query the GeoLite2 web services.
Source: https://dev.maxmind.com/geoip/geolite2-free-geolocation-data

Download link is hidden behind login here: https://www.maxmind.com/en/accounts/current/geoip/downloads

For a specific download link example, see support issue 5938
